import { execFile } from 'node:child_process';
import { existsSync, readFileSync } from 'node:fs';
import { mkdir, readFile, rm, stat, writeFile } from 'node:fs/promises';
import { homedir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { promisify } from 'node:util';

/**
 * Runs the relay in the background as a per-user service on Windows (Task
 * Scheduler), macOS (launchd), and Linux (systemd user unit). None of these
 * need administrator rights. Each starts the relay when the user logs in and
 * restarts it if it exits unexpectedly.
 */

const run = promisify(execFile);

export const SERVICE_NAME = 'crosschat-relay';
const WINDOWS_TASK = 'Crosschat Relay';
const MAC_LABEL = 'dev.crosschat.relay';

export interface ServiceConfig {
  /** The Node.js executable that runs the relay. */
  nodePath: string;
  /** Absolute path to the relay's entry script (dist/index.js). */
  scriptPath: string;
  /** Extra environment for the relay process (for example ELECTRON_RUN_AS_NODE). */
  env?: Record<string, string>;
  dataDir: string;
  port: number;
  host: string;
  allowedHosts?: string;
  logFile: string;
  installedAt: string;
}

export interface ServiceStatus {
  platform: NodeJS.Platform;
  installed: boolean;
  /** Whether the OS reports the service as running. */
  running: boolean;
  /** Whether the relay answers its health check. */
  healthy: boolean;
  config?: ServiceConfig;
  dashboardUrl?: string;
}

/**
 * Where the relay keeps its data and service files when run as a service.
 *
 * On Windows this is %USERPROFILE%\.crosschat-relay rather than AppData:
 * packaged (MSIX) apps such as some terminals and editors have their writes to
 * AppData redirected into a private copy, which Task Scheduler cannot see.
 */
export function appDirectory(platform: NodeJS.Platform = process.platform, env: NodeJS.ProcessEnv = process.env): string {
  if (platform === 'win32') return join(env.USERPROFILE ?? homedir(), `.${SERVICE_NAME}`);
  if (platform === 'darwin') return join(homedir(), 'Library', 'Application Support', SERVICE_NAME);
  return join(env.XDG_DATA_HOME ?? join(homedir(), '.local', 'share'), SERVICE_NAME);
}

const configPath = () => join(appDirectory(), 'service.json');
const stopFlagPath = (dataDir: string) => join(dataDir, 'service.stopped');
export const pidFilePath = (dataDir: string) => join(dataDir, 'relay.pid');

export function relayArguments(config: ServiceConfig): string[] {
  return [
    config.scriptPath,
    '--port',
    String(config.port),
    '--host',
    config.host,
    '--data-dir',
    config.dataDir,
    '--log-file',
    config.logFile,
    ...(config.allowedHosts ? ['--allowed-hosts', config.allowedHosts] : []),
  ];
}

// ------------------------------------------------------------------ files

/** A VBScript launcher: runs the relay with no console window and restarts it until `service stop` leaves a stop flag. */
export function windowsLauncher(config: ServiceConfig): string {
  const quote = (value: string) => `""${value}""`;
  const command = [config.nodePath, ...relayArguments(config)].map(quote).join(' ');
  const envLines = Object.entries(config.env ?? {}).map(
    ([name, value]) => `shell.Environment("PROCESS")("${name}") = "${value.replace(/"/g, '""')}"`,
  );
  return [
    "' Generated by crosschat-relay. Runs the relay hidden and restarts it if it exits.",
    'Set shell = CreateObject("WScript.Shell")',
    'Set fso = CreateObject("Scripting.FileSystemObject")',
    ...envLines,
    `stopFlag = "${stopFlagPath(config.dataDir)}"`,
    'Do',
    `  shell.Run "${command}", 0, True`,
    '  If fso.FileExists(stopFlag) Then Exit Do',
    '  WScript.Sleep 3000',
    'Loop',
    '',
  ].join('\r\n');
}

export function windowsTaskXml(launcherPath: string, userId: string): string {
  const escape = (value: string) => value.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
  return `<?xml version="1.0" encoding="UTF-16"?>
<Task version="1.2" xmlns="http://schemas.microsoft.com/windows/2004/02/mit/task">
  <RegistrationInfo>
    <Description>Crosschat relay: a task inbox for AI agents. Managed with "crosschat-relay service".</Description>
  </RegistrationInfo>
  <Triggers>
    <LogonTrigger>
      <Enabled>true</Enabled>
      <UserId>${escape(userId)}</UserId>
    </LogonTrigger>
  </Triggers>
  <Principals>
    <Principal id="Author">
      <UserId>${escape(userId)}</UserId>
      <LogonType>InteractiveToken</LogonType>
      <RunLevel>LeastPrivilege</RunLevel>
    </Principal>
  </Principals>
  <Settings>
    <MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy>
    <DisallowStartIfOnBatteries>false</DisallowStartIfOnBatteries>
    <StopIfGoingOnBatteries>false</StopIfGoingOnBatteries>
    <AllowHardTerminate>true</AllowHardTerminate>
    <StartWhenAvailable>true</StartWhenAvailable>
    <ExecutionTimeLimit>PT0S</ExecutionTimeLimit>
    <Enabled>true</Enabled>
    <Hidden>false</Hidden>
    <RestartOnFailure>
      <Interval>PT1M</Interval>
      <Count>999</Count>
    </RestartOnFailure>
  </Settings>
  <Actions Context="Author">
    <Exec>
      <Command>wscript.exe</Command>
      <Arguments>//B //Nologo "${escape(launcherPath)}"</Arguments>
    </Exec>
  </Actions>
</Task>
`;
}

export function macPlist(config: ServiceConfig): string {
  const escape = (value: string) => value.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
  const args = [config.nodePath, ...relayArguments(config)].map((value) => `    <string>${escape(value)}</string>`).join('\n');
  const env = Object.entries(config.env ?? {})
    .map(([name, value]) => `    <key>${escape(name)}</key>\n    <string>${escape(value)}</string>`)
    .join('\n');
  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>${MAC_LABEL}</string>
  <key>ProgramArguments</key>
  <array>
${args}
  </array>
${env ? `  <key>EnvironmentVariables</key>\n  <dict>\n${env}\n  </dict>\n` : ''}  <key>RunAtLoad</key>
  <true/>
  <key>KeepAlive</key>
  <true/>
  <key>ThrottleInterval</key>
  <integer>5</integer>
  <key>StandardOutPath</key>
  <string>${escape(serviceOutputPath(config))}</string>
  <key>StandardErrorPath</key>
  <string>${escape(serviceOutputPath(config))}</string>
</dict>
</plist>
`;
}

/** Where launchd writes raw output; the relay logs to its own file, so this only catches early crashes. */
const serviceOutputPath = (config: ServiceConfig) => join(dirname(config.logFile), 'service-output.log');

export function systemdUnit(config: ServiceConfig): string {
  // systemd splits ExecStart on spaces; quote every argument.
  const quote = (value: string) => `"${value.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`;
  const env = Object.entries(config.env ?? {}).map(([name, value]) => `Environment=${quote(`${name}=${value}`)}`);
  return [
    '[Unit]',
    'Description=Crosschat relay (task inbox for AI agents)',
    'After=network-online.target',
    '',
    '[Service]',
    `ExecStart=${[config.nodePath, ...relayArguments(config)].map(quote).join(' ')}`,
    ...env,
    'Restart=always',
    'RestartSec=3',
    '',
    '[Install]',
    'WantedBy=default.target',
    '',
  ].join('\n');
}

// -------------------------------------------------------------- lifecycle

export async function readConfig(): Promise<ServiceConfig | undefined> {
  try {
    return JSON.parse(await readFile(configPath(), 'utf8')) as ServiceConfig;
  } catch {
    return undefined;
  }
}

export interface InstallOptions {
  port?: number;
  host?: string;
  dataDir?: string;
  allowedHosts?: string;
  nodePath?: string;
  scriptPath?: string;
  env?: Record<string, string>;
}

export async function install(options: InstallOptions = {}): Promise<ServiceStatus> {
  const scriptPath = resolve(options.scriptPath ?? join(dirname(fileURLToPath(import.meta.url)), 'index.js'));
  // A script inside the npx cache disappears when the cache is cleaned.
  if (/[\\/]_npx[\\/]/.test(scriptPath)) {
    throw new Error('Install crosschat-relay globally first (npm install -g crosschat-relay), then run "crosschat-relay service install".');
  }
  const dataDir = resolve(options.dataDir ?? appDirectory());
  const nodePath = options.nodePath ?? process.execPath;
  // An Electron binary only behaves as Node.js with ELECTRON_RUN_AS_NODE; without it, the service would open the app instead.
  const env = options.env ?? (nodePath === process.execPath && process.versions.electron ? { ELECTRON_RUN_AS_NODE: '1' } : undefined);
  const config: ServiceConfig = {
    nodePath,
    scriptPath,
    ...(env ? { env } : {}),
    dataDir,
    port: options.port ?? 4318,
    host: options.host ?? '127.0.0.1',
    ...(options.allowedHosts ? { allowedHosts: options.allowedHosts } : {}),
    logFile: join(dataDir, 'logs', 'relay.log'),
    installedAt: new Date().toISOString(),
  };

  // Replace any earlier installation cleanly.
  if (await readConfig()) await uninstall({ keepConfig: true }).catch(() => undefined);

  await mkdir(dirname(config.logFile), { recursive: true });
  await mkdir(appDirectory(), { recursive: true });
  await writeFile(configPath(), `${JSON.stringify(config, null, 2)}\n`);
  await rm(stopFlagPath(dataDir), { force: true });

  switch (process.platform) {
    case 'win32': {
      const launcher = join(appDirectory(), 'relay-launcher.vbs');
      await writeFile(launcher, windowsLauncher(config));
      const xmlPath = join(appDirectory(), 'relay-task.xml');
      const userId = `${process.env.USERDOMAIN ?? ''}\\${process.env.USERNAME ?? ''}`;
      // Task Scheduler expects UTF-16 with a byte order mark.
      await writeFile(xmlPath, `﻿${windowsTaskXml(launcher, userId)}`, 'utf16le');
      await run('schtasks', ['/Create', '/TN', WINDOWS_TASK, '/XML', xmlPath, '/F']);
      await rm(xmlPath, { force: true });
      await run('schtasks', ['/Run', '/TN', WINDOWS_TASK]);
      break;
    }
    case 'darwin': {
      const plistPath = join(homedir(), 'Library', 'LaunchAgents', `${MAC_LABEL}.plist`);
      await mkdir(dirname(plistPath), { recursive: true });
      await writeFile(plistPath, macPlist(config));
      await run('launchctl', ['bootstrap', `gui/${process.getuid!()}`, plistPath]);
      break;
    }
    default: {
      const unitPath = join(homedir(), '.config', 'systemd', 'user', `${SERVICE_NAME}.service`);
      await mkdir(dirname(unitPath), { recursive: true });
      await writeFile(unitPath, systemdUnit(config));
      await run('systemctl', ['--user', 'daemon-reload']);
      await run('systemctl', ['--user', 'enable', '--now', SERVICE_NAME]);
    }
  }
  await waitForHealth(config.port, 15_000);
  return status();
}

export async function uninstall({ keepConfig = false }: { keepConfig?: boolean } = {}): Promise<void> {
  const config = await readConfig();
  await stop().catch(() => undefined);
  switch (process.platform) {
    case 'win32':
      await run('schtasks', ['/Delete', '/TN', WINDOWS_TASK, '/F']).catch(() => undefined);
      await rm(join(appDirectory(), 'relay-launcher.vbs'), { force: true });
      break;
    case 'darwin':
      await rm(join(homedir(), 'Library', 'LaunchAgents', `${MAC_LABEL}.plist`), { force: true });
      break;
    default:
      await run('systemctl', ['--user', 'disable', SERVICE_NAME]).catch(() => undefined);
      await rm(join(homedir(), '.config', 'systemd', 'user', `${SERVICE_NAME}.service`), { force: true });
      await run('systemctl', ['--user', 'daemon-reload']).catch(() => undefined);
  }
  if (config) await rm(stopFlagPath(config.dataDir), { force: true });
  // The data directory (tasks, agents, admin token) is deliberately left in place.
  if (!keepConfig) await rm(configPath(), { force: true });
}

export async function start(): Promise<ServiceStatus> {
  const config = await requireConfig();
  await rm(stopFlagPath(config.dataDir), { force: true });
  switch (process.platform) {
    case 'win32':
      await run('schtasks', ['/Run', '/TN', WINDOWS_TASK]);
      break;
    case 'darwin': {
      const plistPath = join(homedir(), 'Library', 'LaunchAgents', `${MAC_LABEL}.plist`);
      await run('launchctl', ['bootstrap', `gui/${process.getuid!()}`, plistPath]).catch(() => undefined);
      await run('launchctl', ['kickstart', `gui/${process.getuid!()}/${MAC_LABEL}`]);
      break;
    }
    default:
      await run('systemctl', ['--user', 'start', SERVICE_NAME]);
  }
  await waitForHealth(config.port, 15_000);
  return status();
}

/** Stop the relay until the next `start` or the next login. */
export async function stop(): Promise<void> {
  const config = await requireConfig();
  switch (process.platform) {
    case 'win32': {
      // Tell the launcher not to restart it, then end the relay and the launcher.
      await writeFile(stopFlagPath(config.dataDir), new Date().toISOString());
      killRelay(config);
      await run('schtasks', ['/End', '/TN', WINDOWS_TASK]).catch(() => undefined);
      break;
    }
    case 'darwin':
      await run('launchctl', ['bootout', `gui/${process.getuid!()}/${MAC_LABEL}`]).catch(() => undefined);
      break;
    default:
      await run('systemctl', ['--user', 'stop', SERVICE_NAME]);
  }
  await waitFor(async () => !(await isHealthy(config.port)), 10_000);
}

export async function restart(): Promise<ServiceStatus> {
  await stop();
  return start();
}

export async function status(): Promise<ServiceStatus> {
  const config = await readConfig();
  if (!config) return { platform: process.platform, installed: false, running: false, healthy: false };
  const healthy = await isHealthy(config.port);
  return {
    platform: process.platform,
    installed: true,
    running: healthy || isRelayProcessAlive(config),
    healthy,
    config,
    dashboardUrl: `http://localhost:${config.port}/`,
  };
}

/** The last `lines` lines of the relay's log. */
export async function logs(lines = 50): Promise<string> {
  const config = await requireConfig();
  if (!existsSync(config.logFile)) return '';
  const size = (await stat(config.logFile)).size;
  const text = await readFile(config.logFile, 'utf8');
  const tail = text.split(/\r?\n/).slice(-(lines + 1)).join('\n');
  return size > 0 ? tail : '';
}

export async function isHealthy(port: number): Promise<boolean> {
  try {
    const response = await fetch(`http://127.0.0.1:${port}/health`, { signal: AbortSignal.timeout(1500) });
    return response.ok;
  } catch {
    return false;
  }
}

async function waitForHealth(port: number, timeoutMs: number): Promise<void> {
  const healthy = await waitFor(() => isHealthy(port), timeoutMs);
  if (!healthy) throw new Error(`The relay did not become healthy on port ${port}. Check the log with "crosschat-relay service logs".`);
}

async function waitFor(check: () => Promise<boolean>, timeoutMs: number): Promise<boolean> {
  const deadline = Date.now() + timeoutMs;
  while (Date.now() < deadline) {
    if (await check()) return true;
    await new Promise((resolve) => setTimeout(resolve, 300));
  }
  return false;
}

async function requireConfig(): Promise<ServiceConfig> {
  const config = await readConfig();
  if (!config) throw new Error('The relay service is not installed. Run "crosschat-relay service install" first.');
  return config;
}

function relayPid(config: ServiceConfig): number | undefined {
  try {
    const pid = Number(readFileSync(pidFilePath(config.dataDir), 'utf8').trim());
    return Number.isInteger(pid) && pid > 0 ? pid : undefined;
  } catch {
    return undefined;
  }
}

function isRelayProcessAlive(config: ServiceConfig): boolean {
  const pid = relayPid(config);
  if (!pid) return false;
  try {
    process.kill(pid, 0);
    return true;
  } catch {
    return false;
  }
}

function killRelay(config: ServiceConfig): void {
  const pid = relayPid(config);
  if (!pid) return;
  try {
    // Committed SQLite transactions survive an abrupt stop.
    process.kill(pid);
  } catch {
    // Already gone.
  }
}
